#ifndef VERSION_H
#define VERSION_H

#define VER_DATE_INFO_STR           " - 06 July 2021"

#define VER_FILEVERSION             0,2,3,0
#define VER_FILEVERSION_STR         "0.2.3.0\0"

#define VER_PRODUCTVERSION          0,2,3,0
#define VER_PRODUCTVERSION_STR      "0.2\0"

#define VER_COMPANYNAME_STR         "B.VERNOUX"
#define VER_FILEDESCRIPTION_STR     "VNA_Qt for HP8753 VNA"
#define VER_INTERNALNAME_STR        VER_FILEDESCRIPTION_STR
#define VER_LEGALCOPYRIGHT_STR      "B.VERNOUX (c)2019-2021"
#define VER_LEGALTRADEMARKS1_STR    VER_LEGALCOPYRIGHT_STR
#define VER_LEGALTRADEMARKS2_STR    VER_LEGALCOPYRIGHT_STR
#define VER_ORIGINALFILENAME_STR    "VNA_Qt.exe"
#define VER_PRODUCTNAME_STR         "VNA_Qt"

#define VER_COMPANYDOMAIN_STR       "hydrabus.com"

#endif // VERSION_H
